# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-24 12:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u5b66\u6821\u540d\u5b57')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6ce8\u518c\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u5b66\u6821',
                'verbose_name_plural': '\u5b66\u6821',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u7535\u8bdd')),
                ('province', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u7c4d\u8d2f')),
                ('location', models.TextField(blank=True, null=True, verbose_name='\u5730\u5740')),
                ('idcard', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u8eab\u4efd\u8bc1')),
                ('sex', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_client.School', verbose_name='\u6240\u5728\u5b66\u6821')),
            ],
            options={
                'verbose_name': '\u6559\u5e08',
                'verbose_name_plural': '\u6559\u5e08',
            },
        ),
    ]
