# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-24 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u6559\u5e08\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, '\u7537'), (2, '\u5973')], null=True),
        ),
    ]
